version: '3.8'

services:
  sql-server:
    build:
      context: devops/sql server/
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=StrongPassw0rd
      - ACCEPT_EULA=Y
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P StrongPassw0rd -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
  user-api:
    build:
      context: UserApi/
      dockerfile: Dockerfile
    depends_on:
      - sql-server
      - notification-api
    ports:
      - "4000:8080"
  notification-api:
    build:
      context: NotificationApi/
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
  frontend:
    build:
      context: Frontend/
      dockerfile: Dockerfile 
    depends_on:
      - user-api
    ports:
      - "5173:80"